### ISSUE TITLE
Check out CSS index.html

### ISSUE THREAD

**Issue by guillemrima** [jordienr/tax-app#16]
He estado editando el css del fomulario, si os parece  entrad, echadle un ojo a la rama `feat/style-for-form` y decidme si os parece bien el diseño o cambiamos algo antes de hacer pr. 
@jordienr 
@Willy93-coder 
@Dualvicc

**Comment by jordienr** [comment]
yo lo veo bien, y lo podemos cambiar a futuro, dale
