### ISSUE TITLE
CSS & HTML /Budget

### ISSUE THREAD

**Issue by guillemrima** [jordienr/tax-app#31]
He empezado la página budget , tanto el html como el css:
- De momento los botones de abajo no son botones como tal, son div con la imagen y el texto dentro ya que de momento como no se cual será su funcionalidad prefiero mantenerlo así hasta que entremos en detalle.

- Me da un poco de toc que el precio de arriba esté alineado teniendo en cuenta el símbolo del euro, igual tengo que poner un poco de margen a la izquierda para que se centre solo con el número.

- He pillado los mismos colores que la maquetación de Jordi pero como el formulario y esta página tienen paletas distintas habrá que ponerse de acuerdo con que paleta general usar.

Poco más shavales, si os parece bien los mandamos a PR.
![cssBudget](https://user-images.githubusercontent.com/117720260/216759240-2e7448d4-9fe0-4725-85c9-0b385c1b0538.png)

**Comment by Dualvicc** [comment]
Bueno, bonito y barato

**Comment by guillemrima** [comment]
He estado cambiando el estilo del formulario para hacerlo parecido al de budget. De momento la cosa queda así, estaría guay intentar hacer el mismo estilo para la lista con los mismos colores, formatos etc.

Decidme que tal os parece lo de poner el total en el mismo botón de guardar.

![Proyecto nuevo](https://user-images.githubusercontent.com/117720260/216954024-392d951c-b12d-4f59-bc70-72685dc0707b.jpg)

**Comment by jordienr** [comment]
Buena idea, diría que el botón de guardar del form de facturas necesita más padding vertical, 44px de altura mínimo para mobile.
